version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      args:
        - NODE_OPTIONS=--max-old-space-size=1024
    container_name: lectoria_backend
    environment:
      NODE_ENV: production
      DB_PATH: /app/data/lectoria.db
      JWT_SECRET: ${JWT_SECRET:-lectoria_jwt_secret_change_in_production_2024}
      PORT: 3000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data  # SQLite database directory
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - lectoria_network

volumes:
  lectoria_data:
    driver: local

networks:
  lectoria_network:
    driver: bridge