version: '3'

# Simplified Lectoria for ZimaOS
# This compose file is optimized for quick startup

services:
  lectoria:
    image: chicohaager/lectoria:latest
    container_name: lectoria
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUID=1000
      - PGID=1000
    volumes:
      - /DATA/AppData/lectoria/data:/app/data
      - /DATA/AppData/lectoria/uploads:/app/uploads
      - /DATA/AppData/lectoria/logs:/app/logs
    restart: unless-stopped