version: '3.8'

services:
  lectoria:
    build: .
    container_name: lectoria-prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    volumes:
      - /var/lectoria/data:/app/data
      - /var/lectoria/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lectoria-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: lectoria-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - lectoria
    networks:
      - lectoria-network
    restart: unless-stopped

volumes:
  lectoria-data:
    driver: local
  lectoria-uploads:
    driver: local

networks:
  lectoria-network:
    driver: bridge