version: '3.8'

services:
  lectoria:
    image: chicohaager/lectoria:latest
    # Alternative: Build locally (uses main Dockerfile with PUID/PGID support)
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - NODE_OPTIONS=--max-old-space-size=1024
    container_name: lectoria-zimaos
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # JWT_SECRET - provide your own secret or use the generated one below
      # Generate a secure secret: openssl rand -base64 64
      - JWT_SECRET=${JWT_SECRET:-lectoria-zimaos-jwt-secret-2024-change-me}
      - PORT=3000
      - DB_PATH=/app/data/lectoria.db
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-70485760}
      - MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE:-5242880}
      # User/Group ID for proper file permissions
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      # ZimaOS persistent storage paths with explicit bind mounts
      - type: bind
        source: /DATA/AppData/lectoria/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/lectoria/uploads
        target: /app/uploads
      - type: bind
        source: /DATA/AppData/lectoria/logs
        target: /app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - lectoria-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx für SSL/Reverse Proxy
  # Uncomment if you need SSL/HTTPS support
  # nginx:
  #   image: nginx:alpine
  #   container_name: lectoria-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /DATA/AppData/lectoria/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /DATA/AppData/lectoria/ssl:/etc/nginx/ssl:ro
  #     - /DATA/AppData/lectoria/www:/var/www/html:ro
  #   depends_on:
  #     - lectoria
  #   networks:
  #     - lectoria-network
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

networks:
  lectoria-network:
    driver: bridge