version: '3.8'

services:
  lectoria:
    image: chicohaager/lectoria:latest
    # Alternative: Build locally
    # build:
    #   context: .
    #   dockerfile: Dockerfile.optimized
    #   args:
    #     - NODE_OPTIONS=--max-old-space-size=1024
    container_name: lectoria-zimaos
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-change-me-lectoria-jwt-secret-zimaos-2024}
      - PORT=3000
      - DB_PATH=/app/data/lectoria.db
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-70485760}
      - MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE:-5242880}
    volumes:
      # ZimaOS persistent storage paths
      - lectoria-data:/app/data
      - lectoria-uploads:/app/uploads
      - lectoria-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - lectoria-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx für SSL/Reverse Proxy
  # Uncomment if you need SSL/HTTPS support
  # nginx:
  #   image: nginx:alpine
  #   container_name: lectoria-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /DATA/AppData/lectoria/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /DATA/AppData/lectoria/ssl:/etc/nginx/ssl:ro
  #     - /DATA/AppData/lectoria/www:/var/www/html:ro
  #   depends_on:
  #     - lectoria
  #   networks:
  #     - lectoria-network
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

volumes:
  # Named volumes für bessere Portabilität
  lectoria-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /DATA/AppData/lectoria/data
      
  lectoria-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /DATA/AppData/lectoria/uploads

  lectoria-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /DATA/AppData/lectoria/logs

networks:
  lectoria-network:
    driver: bridge